version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run: echo $GOOGLE_SERVICES | base64 -di > libraries/authenticator/google-services.json
      - run:
          command: ./gradlew build
