version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run: echo "storePassword=$STORE_PASSWORD" >> keystore.properties
      - run: echo "keyAlias=$KEY_ALIAS" >> keystore.properties
      - run: echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
      - run: echo "storeFile=app/perfectus.jsk" >> keystore.properties
      - run: echo $KEYSTORE_JSK | base64 -d > app/perfectus.jsk
      - run: echo $GOOGLE_SERVICES | base64 -di > libraries/authenticator/google-services.json
      - run: echo $GOOGLE_API | base64 -di > fastlane/api.json
      - run:
          command: ./gradlew build
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Execute fastlane
          command: bundle exec fastlane playstore
