version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    environment:
      // Circle CI build failure fix
      // https://github.com/circleci/circleci-docs/issues/2945#issuecomment-471637158
      // In the case of test failure switch back to -Xmx4g -Dorg.gradle.daemon=false
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
      JVM_OPTS: -Xmx4g

    steps:
      - checkout
      - run: echo "storePassword=$STORE_PASSWORD" >> keystore.properties
      - run: echo "keyAlias=$KEY_ALIAS" >> keystore.properties
      - run: echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
      - run: echo "storeFile=perfectus.jsk" >> keystore.properties
      - run: echo $KEYSTORE_JSK | base64 -d > app/perfectus.jsk
      - run: echo $GOOGLE_SERVICE | base64 -di > libraries/authenticator/google-services.json
      - run: echo $GOOGLE_API | base64 -di > fastlane/api.json
      - run:
          command: ./gradlew build
      - run:
          name: Install fastlane
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ];
            then
              bundle install
            else
              echo "Install fastlane step skipped"
            fi
      - run:
          name: Execute fastlane
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ];
            then
              bundle exec fastlane playstore
            else
              echo "Execute fastlane step skipped"
            fi
